package pyrand

// Parity tests against reference vectors generated by the local CPython
// (see testdata/pyrand_vectors.json, produced by gen_pyrand_vectors.py).
// If any of these fail, the Go engine can no longer claim byte-identical
// output with the Python Math SDK - fix pyrand before touching game logic.

import (
	"encoding/json"
	"os"
	"strconv"
	"testing"
)

type vectors struct {
	RandomSeed1     []string  `json:"random_seed_1"`
	RandomSeed12345 []string  `json:"random_seed_12345"`
	RandomSeed0     []string  `json:"random_seed_0"`
	RandomSeedBig   []string  `json:"random_seed_1099511627783"`
	GetRandBits     []uint64  `json:"getrandbits"`
	Randrange628    []int     `json:"randrange_628"`
	Randint04       []int     `json:"randint_0_4"`
	Uniform0437     []string  `json:"uniform_0_437"`
	ChoicesWeights  []int     `json:"choices_weights"`
	Shuffle20Seed0  []int     `json:"shuffle_20_seed0"`
	Interleaved     []any     `json:"interleaved_1234"`
}

func loadVectors(t *testing.T) vectors {
	t.Helper()
	raw, err := os.ReadFile("testdata/pyrand_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v vectors
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	return v
}

func mustFloat(t *testing.T, s string) float64 {
	t.Helper()
	f, err := strconv.ParseFloat(s, 64)
	if err != nil {
		t.Fatalf("parse float %q: %v", s, err)
	}
	return f
}

func TestRandomFloats(t *testing.T) {
	v := loadVectors(t)
	cases := map[uint64][]string{
		1:             v.RandomSeed1,
		12345:         v.RandomSeed12345,
		0:             v.RandomSeed0,
		1099511627783: v.RandomSeedBig, // 2**40 + 7: exercises multi-word seeding
	}
	for seed, want := range cases {
		r := New(seed)
		for i, ws := range want {
			got := r.Random()
			if got != mustFloat(t, ws) {
				t.Fatalf("seed %d draw %d: got %v want %s", seed, i, got, ws)
			}
		}
	}
}

func TestGetRandBits(t *testing.T) {
	v := loadVectors(t)
	r := New(7)
	ks := []uint{1, 3, 8, 16, 31, 32, 33, 53, 64}
	for i, k := range ks {
		got := r.GetRandBits(k)
		if got != v.GetRandBits[i] {
			t.Fatalf("getrandbits(%d) draw %d: got %d want %d", k, i, got, v.GetRandBits[i])
		}
	}
}

func TestRandRangeAndRandInt(t *testing.T) {
	v := loadVectors(t)
	r := New(42)
	for i, want := range v.Randrange628 {
		if got := r.RandRange(628); got != want {
			t.Fatalf("randrange(628) draw %d: got %d want %d", i, got, want)
		}
	}
	r = New(42)
	for i, want := range v.Randint04 {
		if got := r.RandInt(0, 4); got != want {
			t.Fatalf("randint(0,4) draw %d: got %d want %d", i, got, want)
		}
	}
}

func TestUniform(t *testing.T) {
	v := loadVectors(t)
	r := New(99)
	for i, ws := range v.Uniform0437 {
		if got := r.Uniform(0, 437.0); got != mustFloat(t, ws) {
			t.Fatalf("uniform draw %d: got %v want %s", i, got, ws)
		}
	}
}

func TestWeightedChoice(t *testing.T) {
	v := loadVectors(t)
	r := New(5)
	w := []float64{10, 1, 5, 0.5, 2}
	for i, want := range v.ChoicesWeights {
		if got := r.WeightedChoiceIndex(w); got != want {
			t.Fatalf("choices draw %d: got %d want %d", i, got, want)
		}
	}
}

func TestShuffle(t *testing.T) {
	v := loadVectors(t)
	r := New(0)
	x := make([]int, 20)
	for i := range x {
		x[i] = i
	}
	r.Shuffle(len(x), func(i, j int) { x[i], x[j] = x[j], x[i] })
	for i := range x {
		if x[i] != v.Shuffle20Seed0[i] {
			t.Fatalf("shuffle mismatch at %d: got %v want %v", i, x, v.Shuffle20Seed0)
		}
	}
}

// TestInterleaved runs a mixed call sequence to prove state stays in sync
// across different draw types (the real engine interleaves all of them).
func TestInterleaved(t *testing.T) {
	v := loadVectors(t)
	r := New(1234)

	if got := r.Random(); got != mustFloat(t, v.Interleaved[0].(string)) {
		t.Fatalf("interleaved[0]: got %v", got)
	}
	if got := r.GetRandBits(10); got != uint64(v.Interleaved[1].(float64)) {
		t.Fatalf("interleaved[1]: got %v", got)
	}
	if got := r.RandRange(300); got != int(v.Interleaved[2].(float64)) {
		t.Fatalf("interleaved[2]: got %v", got)
	}
	if got := r.Uniform(0, 55.5); got != mustFloat(t, v.Interleaved[3].(string)) {
		t.Fatalf("interleaved[3]: got %v", got)
	}
	if got := r.WeightedChoiceIndex([]float64{4, 3, 2, 1}); got != int(v.Interleaved[4].(float64)) {
		t.Fatalf("interleaved[4]: got %v", got)
	}
	y := []int{0, 1, 2, 3, 4, 5, 6}
	r.Shuffle(len(y), func(i, j int) { y[i], y[j] = y[j], y[i] })
	wantY := v.Interleaved[5].([]any)
	for i := range y {
		if y[i] != int(wantY[i].(float64)) {
			t.Fatalf("interleaved shuffle: got %v want %v", y, wantY)
		}
	}
	if got := r.Random(); got != mustFloat(t, v.Interleaved[6].(string)) {
		t.Fatalf("interleaved[6]: got %v", got)
	}
}
